In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('survey_results_public2019.csv')
schema_df = pd.read_csv('survey_results_schema2019.csv', index_col = 'Column')

In [29]:
pd.set_option('Display.max_columns',85)
pd.set_option('Display.max_rows',85)

In [30]:
df['ConvertedComp'].head(50)

0           NaN
1           NaN
2        8820.0
3       61000.0
4           NaN
5      366420.0
6           NaN
7           NaN
8       95179.0
9       13293.0
10          NaN
11          NaN
12      90000.0
13      57060.0
14          NaN
15     455352.0
16      65277.0
17      21996.0
18      31140.0
19      41244.0
20          NaN
21     103000.0
22      69000.0
23      26388.0
24       6300.0
25     114000.0
26          NaN
27          NaN
28     100000.0
29      90417.0
30          NaN
31    1100000.0
32       8400.0
33          NaN
34      80000.0
35      20628.0
36          NaN
37      51312.0
38     156000.0
39          NaN
40          NaN
41          NaN
42      20623.0
43      87996.0
44     175000.0
45          NaN
46     187000.0
47          NaN
48      60000.0
49       5597.0
Name: ConvertedComp, dtype: float64

In [31]:
df['ConvertedComp'].median() #gives median of a single columns or series

57287.0

In [32]:
df.median() #gives median of all columns having numeric value

C:\Users\Ashuh\AppData\Local\Temp/ipykernel_11256/2684045094.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.median() #gives median of all columns having numeric value

Respondent       44442.0
CompTotal        62000.0
ConvertedComp    57287.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [33]:
df[['ConvertedComp','Respondent','CompTotal','WorkWeekHrs','CodeRevHrs','Age']].median()#gives median of all columns having numeric value

ConvertedComp    57287.0
Respondent       44442.0
CompTotal        62000.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [34]:
df.describe()#gives overview of all columns having numeric value

,Respondent,CompTotal,ConvertedComp,WorkWeekHrs,CodeRevHrs,Age
count,88883.000000,5.594500e+04,5.582300e+04,64503.000000,49790.000000,79210.000000
mean,44442.000000,5.519014e+11,1.271107e+05,42.127197,5.084308,30.336699
std,25658.456325,7.331926e+13,2.841523e+05,37.287610,5.513931,9.178390
min,1.000000,0.000000e+00,0.000000e+00,1.000000,0.000000,1.000000
25%,22221.500000,2.000000e+04,2.577750e+04,40.000000,2.000000,24.000000
50%,44442.000000,6.200000e+04,5.728700e+04,40.000000,4.000000,29.000000
75%,66662.500000,1.200000e+05,1.000000e+05,44.750000,6.000000,35.000000
max,88883.000000,1.000000e+16,2.000000e+06,4850.000000,99.000000,99.000000

In [35]:
df['ConvertedComp'].count()#it is showing the number of people responded to convertedcomp in other words it exclude naan

55823

In [36]:
df['Hobbyist'].value_counts()#it differentiate b/w different type of response or value

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [37]:
df['SocialMedia']

0          Twitter
1        Instagram
2           Reddit
3           Reddit
4         Facebook
           ...
88878      YouTube
88879          NaN
88880          NaN
88881          NaN
88882     WhatsApp
Name: SocialMedia, Length: 88883, dtype: object

In [38]:
df['SocialMedia'].value_counts()

Reddit                      14374
YouTube                     13830
WhatsApp                    13347
Facebook                    13178
Twitter                     11398
Instagram                    6261
I don't use social media     5554
LinkedIn                     4501
WeChat 微信                     667
Snapchat                      628
VK ВКонта́кте                 603
Weibo 新浪微博                     56
Youku Tudou 优酷                 21
Hello                          19
Name: SocialMedia, dtype: int64

In [39]:
schema_df.loc['SocialMedia']

QuestionText    What social media site do you use the most?
Name: SocialMedia, dtype: object

In [40]:
df['SocialMedia'].value_counts(normalize = True) #gives percent of unique counts

Reddit                      0.170233
YouTube                     0.163791
WhatsApp                    0.158071
Facebook                    0.156069
Twitter                     0.134988
Instagram                   0.074150
I don't use social media    0.065777
LinkedIn                    0.053306
WeChat 微信                   0.007899
Snapchat                    0.007437
VK ВКонта́кте               0.007141
Weibo 新浪微博                  0.000663
Youku Tudou 优酷              0.000249
Hello                       0.000225
Name: SocialMedia, dtype: float64

In [41]:
#group a data

In [42]:
df['Country'].value_counts

<bound method IndexOpsMixin.value_counts of 0                United Kingdom
1        Bosnia and Herzegovina
2                      Thailand
3                 United States
4                       Ukraine
                  ...
88878                    Canada
88879                       NaN
88880                       NaN
88881                       NaN
88882                     Spain
Name: Country, Length: 88883, dtype: object>

In [43]:
 df.groupby(['Country'])  # to group by country

In [44]:
country_grp =  df.groupby(['Country']) #assigned variable

In [45]:
country_grp.get_group('India') #to get group by data by country $imp

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
7,8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Engineer, site reliability",8,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;P...,Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;R...,Cassandra;DynamoDB;Elasticsearch;Firebase;Mong...,AWS;Docker;Heroku;Linux;MacOS;Slack,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Express;Flask;React.js;Spring,Django;Express;Flask;React.js;Vue.js,Hadoop;Node.js;Pandas,Ansible;Apache Spark;Chef;Hadoop;Node.js;Panda...,Atom;IntelliJ;IPython / Jupyter;PyCharm;Visual...,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful across many domains and could change ma...,Yes,SIGH,Yes,YouTube,In real life (in person),Handle,2012,A few times per week,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
9,10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,"10,000 or more employees",Data or business analyst;Data scientist or mac...,12,20,10,Slightly dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",3-4 years ago,NaN,No,"Languages, frameworks, and other technologies ...",NaN,INR,Indian rupee,950000.0,Yearly,13293.0,70.0,There's no schedule or spec; I work on what se...,NaN,A few days each month,Home,Far above average,"Yes, because I see value in code review",4.0,"Yes, it's part of our process",NaN,NaN,C#;Go;JavaScript;Python;R;SQL,C#;Go;JavaScript;Kotlin;Python;R;SQL,Elasticsearch;MongoDB;Microsoft SQL Server;MyS...,Elasticsearch;MongoDB;Microsoft SQL Server,Linux;Windows,Android;Linux;Raspberry Pi;Windows,Angular/Angular.js;ASP.NET;Django;Express;Flas...,Angular/Angular.js;ASP.NET;Django;Express;Flas...,.NET;Node.js;Pandas;Torch/PyTorch,.NET;Node.js;TensorFlow;Torch/PyTorch,Android Studio;Eclipse;IPython / Jupyter;Notep...,Windows,NaN,Not at all,Useful for immutable record keeping outside of...,No,Yes,Yes,YouTube,Neither,Screen Name,NaN,Multiple times per day,Find answers to specific questions;Get a sense...,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
14,15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,Student,3,13,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",I've never had a job,NaN,NaN,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;...,Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;HTM...,MariaDB;MySQL;Oracle;SQLite,MariaDB;MongoDB;Microsoft SQL Server;MySQL;Ora...,Linux;Windows,Android;Google Cloud Platform;iOS;Linux;MacOS;...,NaN,Angular/Angular.js;ASP.NET;Django;Drupal;jQuer...,NaN,.NET;.NET Core;Node.js;TensorFlow;Unity 3D;Unr...,Atom;NetBeans;Notepad++;Sublime Text;Vim,Linux-based,Development,NaN,NaN,Yes,Yes,What?,YouTube,In real life (in person),NaN,2018,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
49,50,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,"10,000 or more employees","Developer, back-end;DevOps specialist",7,15,2,Slightly satisfied,Very satisfied,Very confident,Not sure,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,Specific department or team I'd be working on;...,I was preparing for a job search,INR,Indian rupee,400000.0,Yearly,5597.0,7.0,There is a schedule and/or spec (made by me or...,Meetings;Time spent commuting,Less than once per month / Never,"Other place, such as a coworking space or cafe",Average,No,NaN,"Yes, it's not part of our process but the deve...","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,HTML/CSS;JavaScript;Python,Elasticsearch;Firebase;MariaDB;MongoDB;MySQL;O...,Firebase;PostgreSQL;Redis;Other(s):,Arduino;AWS;Heroku;Linux;MacOS;Raspberry Pi;Wo...,AWS;Docker;Heroku;Kubernetes;Linux;MacOS;WordP...,Django;Express;Flask;jQuery,Express;Flask;jQuery;React.js;Vue.js,Node.js,Node.js,Notepad++;Visual Studio Code,MacOS,Testing,Not at all,Useful for immutable record keeping outside of...,Yes,Also Yes,What?,YouTube,In real life (in person),Username,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,NaN,South Asian,No,Too long,Easy
64,65,I am a developer by profession,Yes,Never,NaN,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",NaN,20 to 99 employees,"Developer, front-end;Developer, mobile",2,17,2,Very satisfied,Very satisfied,Very confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Solve a brain-teaser style puzz...,No,"Languages, frameworks, and other technologies ...","My job status changed (promotion, new job, etc.)",INR,Indian rupee,NaN,Monthly,NaN,48.0,There's no schedule or spec; I work on what se...,NaN,About half the time,Office,Average,"Yes, because I see value in code review",NaN,"Yes, it's not part of our process but the deve...",Not sure,NaN,Assembly;C;C++;C#;HTML/CSS;Java,Kotlin,Firebase;MySQL;Oracle;SQLite,Firebase;SQLite,Android,Android,ASP.NET,NaN,NaN,NaN,Android Studio;IntelliJ,Linux-based,NaN,NaN,NaN,Yes,Yes,What?,WhatsApp,In real life (in person),NaN,2017,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,A few times per week,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Not sure,A lot more welcome now than last year,NaN,21.0,Man,No,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88808,77339,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Taken an online course in programming or softw...,"1,000 to 4,999 employees",NaN,1,27,1,NaN,NaN,Somewhat confident,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other(s):,Python;SQL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,No,YouTube,Online,UserID,2019,Less than once per month or monthly,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I didn't know that Stack Overflow had a jo...","No, I've heard of them, but I am not part of a...","Yes, somewhat",Not applicable - I did not use Stack Overflow ...,Tech articles written by other developers;Indu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88825,79795,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,500 to 999 employees,"Developer, QA or test",6,17,5,NaN,NaN,Somewhat confident,No,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;Python;SQL;VBA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Apache Spark;Chef;Puppet,NaN,PyCharm;Vim,Linux-based,Development;Testing;Production;Outside of work...,Not at all,NaN,No,Yes,What?,Instagram,In real life (in person),Username,2018,A few times per month or weekly,Find answers to specific questions,Less than once per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Somewhat more welcome now than last year,Tech meetups or events in your area;Courses on...,NaN,Man,No,Straight / Heterosexual,NaN,No,Too long,Difficult
88852,83862,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,Participated in a hackathon,NaN,Data or business analyst;Student,1,18,Less than 1 year,NaN,NaN,Very confident,Not sure,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;C++;HTML/CSS;Java;JavaScript;Object...,NaN,MySQL,DynamoDB;Elasticsearch;MongoDB,Android;AWS;Google Cloud Platform;WordPress,IBM Cloud or Watson,Laravel,Angular/Angular.js;Laravel;Vue.js,NaN,Node.js,Android Studio;Atom;IntelliJ;Komodo;NetBeans;N...,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,No,Yes,What?,Twitter,Online,UserID,2012,A few times per month or weekly,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was much faster,0-10 minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
88853,84299,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,100 to 499 employees,"Developer, back-end;Developer, front-end;Devel...",12,25,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python;Swift;TypeScript,HTML/CSS;Java;JavaScript,MongoDB;Redis;SQLite,MongoDB;Redis,NaN,NaN,Angular/Angular.js;Express;jQuery;React.js;Oth...,Express;React.js;Other(s):,Node.js,Node.js,IntelliJ;Notepad++;Visual Studio Code;Xcode,Windows,NaN,NaN,NaN,Yes,"Fortunately, someone else has that title",What?,LinkedIn,NaN,NaN,2011,A few times per month or weekly,Find answers to specific questions;Contribute ...,Less than once per week,Stack Overflow was much faster,60+ minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat more welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88864,86012,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Another engineering discipline (ex. civil, ele...","Taught yourself a new language, framework, or ...",100 to 499 employees,Academic researcher;Educator,5,15,NaN,NaN,NaN,Somewhat confident,No,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript,C++;Python,MySQL,NaN,Other(s):,Other(s):,NaN,NaN,NaN,NaN,Notepad++,Linux-based,I do not use containers,NaN,NaN,No,Also Yes,What?,I don't use social media,Online,Username,2014,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was much faster,11-30 minutes,Yes,NaN,"No, I knew that Stack Overflow had a job board...",Yes,"Yes, somewhat",Not applicable - I did not use Stack Overflow ...,Industry news about technologies you're intere...,24.0,Man,No,NaN,South Asian,NaN,Appropriate in length,Easy

In [46]:
filt = df['Country'] == 'India'
df.loc[filt]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
7,8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Engineer, site reliability",8,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;P...,Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;R...,Cassandra;DynamoDB;Elasticsearch;Firebase;Mong...,AWS;Docker;Heroku;Linux;MacOS;Slack,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Express;Flask;React.js;Spring,Django;Express;Flask;React.js;Vue.js,Hadoop;Node.js;Pandas,Ansible;Apache Spark;Chef;Hadoop;Node.js;Panda...,Atom;IntelliJ;IPython / Jupyter;PyCharm;Visual...,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful across many domains and could change ma...,Yes,SIGH,Yes,YouTube,In real life (in person),Handle,2012,A few times per week,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
9,10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,"10,000 or more employees",Data or business analyst;Data scientist or mac...,12,20,10,Slightly dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",3-4 years ago,NaN,No,"Languages, frameworks, and other technologies ...",NaN,INR,Indian rupee,950000.0,Yearly,13293.0,70.0,There's no schedule or spec; I work on what se...,NaN,A few days each month,Home,Far above average,"Yes, because I see value in code review",4.0,"Yes, it's part of our process",NaN,NaN,C#;Go;JavaScript;Python;R;SQL,C#;Go;JavaScript;Kotlin;Python;R;SQL,Elasticsearch;MongoDB;Microsoft SQL Server;MyS...,Elasticsearch;MongoDB;Microsoft SQL Server,Linux;Windows,Android;Linux;Raspberry Pi;Windows,Angular/Angular.js;ASP.NET;Django;Express;Flas...,Angular/Angular.js;ASP.NET;Django;Express;Flas...,.NET;Node.js;Pandas;Torch/PyTorch,.NET;Node.js;TensorFlow;Torch/PyTorch,Android Studio;Eclipse;IPython / Jupyter;Notep...,Windows,NaN,Not at all,Useful for immutable record keeping outside of...,No,Yes,Yes,YouTube,Neither,Screen Name,NaN,Multiple times per day,Find answers to specific questions;Get a sense...,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
14,15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,Student,3,13,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",I've never had a job,NaN,NaN,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;...,Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;HTM...,MariaDB;MySQL;Oracle;SQLite,MariaDB;MongoDB;Microsoft SQL Server;MySQL;Ora...,Linux;Windows,Android;Google Cloud Platform;iOS;Linux;MacOS;...,NaN,Angular/Angular.js;ASP.NET;Django;Drupal;jQuer...,NaN,.NET;.NET Core;Node.js;TensorFlow;Unity 3D;Unr...,Atom;NetBeans;Notepad++;Sublime Text;Vim,Linux-based,Development,NaN,NaN,Yes,Yes,What?,YouTube,In real life (in person),NaN,2018,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
49,50,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,"10,000 or more employees","Developer, back-end;DevOps specialist",7,15,2,Slightly satisfied,Very satisfied,Very confident,Not sure,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,Specific department or team I'd be working on;...,I was preparing for a job search,INR,Indian rupee,400000.0,Yearly,5597.0,7.0,There is a schedule and/or spec (made by me or...,Meetings;Time spent commuting,Less than once per month / Never,"Other place, such as a coworking space or cafe",Average,No,NaN,"Yes, it's not part of our process but the deve...","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,HTML/CSS;JavaScript;Python,Elasticsearch;Firebase;MariaDB;MongoDB;MySQL;O...,Firebase;PostgreSQL;Redis;Other(s):,Arduino;AWS;Heroku;Linux;MacOS;Raspberry Pi;Wo...,AWS;Docker;Heroku;Kubernetes;Linux;MacOS;WordP...,Django;Express;Flask;jQuery,Express;Flask;jQuery;React.js;Vue.js,Node.js,Node.js,Notepad++;Visual Studio Code,MacOS,Testing,Not at all,Useful for immutable record keeping outside of...,Yes,Also Yes,What?,YouTube,In real life (in person),Username,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,NaN,South Asian,No,Too long,Easy
64,65,I am a developer by profession,Yes,Never,NaN,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",NaN,20 to 99 employees,"Developer, front-end;Developer, mobile",2,17,2,Very satisfied,Very satisfied,Very confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Solve a brain-teaser style puzz...,No,"Languages, frameworks, and other technologies ...","My job status changed (promotion, new job, etc.)",INR,Indian rupee,NaN,Monthly,NaN,48.0,There's no schedule or spec; I work on what se...,NaN,About half the time,Office,Average,"Yes, because I see value in code review",NaN,"Yes, it's not part of our process but the deve...",Not sure,NaN,Assembly;C;C++;C#;HTML/CSS;Java,Kotlin,Firebase;MySQL;Oracle;SQLite,Firebase;SQLite,Android,Android,ASP.NET,NaN,NaN,NaN,Android Studio;IntelliJ,Linux-based,NaN,NaN,NaN,Yes,Yes,What?,WhatsApp,In real life (in person),NaN,2017,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,A few times per week,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Not sure,A lot more welcome now than last year,NaN,21.0,Man,No,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88808,77339,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Taken an online course in programming or softw...,"1,000 to 4,999 employees",NaN,1,27,1,NaN,NaN,Somewhat confident,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other(s):,Python;SQL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,No,YouTube,Online,UserID,2019,Less than once per month or monthly,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I didn't know that Stack Overflow had a jo...","No, I've heard of them, but I am not part of a...","Yes, somewhat",Not applicable - I did not use Stack Overflow ...,Tech articles written by other developers;Indu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88825,79795,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,500 to 999 employees,"Developer, QA or test",6,17,5,NaN,NaN,Somewhat confident,No,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;Python;SQL;VBA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Apache Spark;Chef;Puppet,NaN,PyCharm;Vim,Linux-based,Development;Testing;Production;Outside of work...,Not at all,NaN,No,Yes,What?,Instagram,In real life (in person),Username,2018,A few times per month or weekly,Find answers to specific questions,Less than once per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Somewhat more welcome now than last year,Tech meetups or events in your area;Courses on...,NaN,Man,No,Straight / Heterosexual,NaN,No,Too long,Difficult
88852,83862,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,Participated in a hackathon,NaN,Data or business analyst;Student,1,18,Less than 1 year,NaN,NaN,Very confident,Not sure,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;C++;HTML/CSS;Java;JavaScript;Object...,NaN,MySQL,DynamoDB;Elasticsearch;MongoDB,Android;AWS;Google Cloud Platform;WordPress,IBM Cloud or Watson,Laravel,Angular/Angular.js;Laravel;Vue.js,NaN,Node.js,Android Studio;Atom;IntelliJ;Komodo;NetBeans;N...,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,No,Yes,What?,Twitter,Online,UserID,2012,A few times per month or weekly,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was much faster,0-10 minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
88853,84299,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,100 to 499 employees,"Developer, back-end;Developer, front-end;Devel...",12,25,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python;Swift;TypeScript,HTML/CSS;Java;JavaScript,MongoDB;Redis;SQLite,MongoDB;Redis,NaN,NaN,Angular/Angular.js;Express;jQuery;React.js;Oth...,Express;React.js;Other(s):,Node.js,Node.js,IntelliJ;Notepad++;Visual Studio Code;Xcode,Windows,NaN,NaN,NaN,Yes,"Fortunately, someone else has that title",What?,LinkedIn,NaN,NaN,2011,A few times per month or weekly,Find answers to specific questions;Contribute ...,Less than once per week,Stack Overflow was much faster,60+ minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat more welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88864,86012,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Another engineering discipline (ex. civil, ele...","Taught yourself a new language, framework, or ...",100 to 499 employees,Academic researcher;Educator,5,15,NaN,NaN,NaN,Somewhat confident,No,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript,C++;Python,MySQL,NaN,Other(s):,Other(s):,NaN,NaN,NaN,NaN,Notepad++,Linux-based,I do not use containers,NaN,NaN,No,Also Yes,What?,I don't use social media,Online,Username,2014,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was much faster,11-30 minutes,Yes,NaN,"No, I knew that Stack Overflow had a job board...",Yes,"Yes, somewhat",Not applicable - I did not use Stack Overflow ...,Industry news about technologies you're intere...,24.0,Man,No,NaN,South Asian,NaN,Appropriate in length,Easy

In [47]:
df.loc[filt]['SocialMedia'].value_counts()

WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: SocialMedia, dtype: int64

In [48]:
country_grp['SocialMedia'].value_counts().loc['India']

SocialMedia
WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: SocialMedia, dtype: int64

In [49]:
country_grp['ConvertedComp'].median()

Country
Afghanistan                               6222.0
Albania                                  10818.0
Algeria                                   7878.0
Andorra                                 160931.0
Angola                                    7764.0
                                          ...
Venezuela, Bolivarian Republic of...      6384.0
Viet Nam                                 11892.0
Yemen                                    11940.0
Zambia                                    5040.0
Zimbabwe                                 19200.0
Name: ConvertedComp, Length: 179, dtype: float64

In [50]:
country_grp['ConvertedComp'].median().loc['Germany']

63016.0

In [51]:
country_grp['ConvertedComp'].median().loc['India']

10080.0

In [52]:
country_grp['ConvertedComp'].agg(['median','mean']).loc['India']

median    10080.000000
mean      28057.664916
Name: India, dtype: float64

In [56]:
filt = df['Country'] == 'India'
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

3105

In [67]:
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [70]:
country_res = df['Country'].value_counts()

In [71]:
country_res

United States        20949
India                 9061
Germany               5866
United Kingdom        5737
Canada                3395
                     ...
Tonga                    1
Timor-Leste              1
North Korea              1
Brunei Darussalam        1
Chad                     1
Name: Country, Length: 179, dtype: int64

In [73]:
num_of_country_uses_python = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

In [74]:
num_of_country_uses_python

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [81]:
python_df = pd.concat([country_res, num_of_country_uses_python], axis = 'columns', sort = False)

In [82]:
python_df

                   Country  LanguageWorkedWith
United States        20949               10083
India                 9061                3105
Germany               5866                2451
United Kingdom        5737                2384
Canada                3395                1558
...                    ...                 ...
Tonga                    1                   0
Timor-Leste              1                   1
North Korea              1                   0
Brunei Darussalam        1                   0
Chad                     1                   0

[179 rows x 2 columns]

In [88]:
python_df = python_df.rename(columns={'Country': 'Number of responded','LanguageWorkedWith':'Number of people knows python'})

In [87]:
python_df

,Number of responded from each country,Number of people knows python
United States,20949,10083
India,9061,3105
Germany,5866,2451
United Kingdom,5737,2384
Canada,3395,1558
...,...,...
Tonga,1,0
Timor-Leste,1,1
North Korea,1,0
Brunei Darussalam,1,0
Chad,1,0

In [89]:
python_df['pct_knows_python'] = (python_df['Number of people knows python'] / python_df['Number of responded from each country'])* 100

In [90]:
python_df

,Number of responded from each country,Number of people knows python,pct_knows_python
United States,20949,10083,48.131176
India,9061,3105,34.267741
Germany,5866,2451,41.783157
United Kingdom,5737,2384,41.554820
Canada,3395,1558,45.891016
...,...,...,...
Tonga,1,0,0.000000
Timor-Leste,1,1,100.000000
North Korea,1,0,0.000000
Brunei Darussalam,1,0,0.000000
Chad,1,0,0.000000

In [93]:
python_df.sort_values(by='pct_knows_python', ascending = False)

,Number of responded from each country,Number of people knows python,pct_knows_python
Sao Tome and Principe,1,1,100.000000
Timor-Leste,1,1,100.000000
Dominica,1,1,100.000000
Niger,1,1,100.000000
Turkmenistan,7,6,85.714286
...,...,...,...
Cape Verde,3,0,0.000000
Lao People's Democratic Republic,3,0,0.000000
Malawi,2,0,0.000000
Liberia,2,0,0.000000
Chad,1,0,0.000000

In [95]:
python_df.sort_values(by='pct_knows_python', ascending = False).head(60)

,Number of responded from each country,Number of people knows python,pct_knows_python
Sao Tome and Principe,1,1,100.000000
Timor-Leste,1,1,100.000000
Dominica,1,1,100.000000
Niger,1,1,100.000000
Turkmenistan,7,6,85.714286
Mauritania,7,5,71.428571
Guinea,3,2,66.666667
Bahamas,3,2,66.666667
Guyana,3,2,66.666667
Uganda,72,47,65.277778
Iceland,49,30,61.224490
Haiti,5,3,60.000000
Benin,5,3,60.000000
Namibia,5,3,60.000000
"Congo, Republic of the...",7,4,57.142857
Oman,11,6,54.545455
Cuba,30,16,53.333333
Republic of Korea,39,20,51.282051
San Marino,2,1,50.000000
Sierra Leone,2,1,50.000000
Monaco,4,2,50.000000
South Korea,160,80,50.000000
Bhutan,2,1,50.000000
Seychelles,2,1,50.000000
Chile,206,102,49.514563
Finland,546,266,48.717949
Kenya,249,120,48.192771
United States,20949,10083,48.131176
Israel,952,457,48.004202
Ecuador,82,39,47.560976
Taiwan,187,88,47.058824
Montenegro,17,8,47.058824
Mongolia,17,8,47.058824
Switzerland,978,460,47.034765
United Republic of Tanzania,32,15,46.875000
Hong Kong (S.A.R.),188,88,46.808511
Japan,391,182,46.547315
Maldives,13,6,46.153846
Canada,3395,1558,45.891016
Singapore,303,139,45.874587
New Zealand,524,236,45.038168
China,664,297,44.728916
Honduras,27,12,44.444444
France,2391,1054,44.081974
Iraq,39,17,43.589744
Thailand,214,92,42.990654
Democratic Republic of the Congo,7,3,42.857143
Nepal,237,101,42.616034
Estonia,195,82,42.051282
Russian Federation,1694,708,41.794569
Germany,5866,2451,41.783157
Ireland,501,209,41.716567
Rwanda,12,5,41.666667
United Kingdom,5737,2384,41.554820
Australia,1903,790,41.513400
Netherlands,1852,767,41.414687
Luxembourg,61,25,40.983607
Belgium,727,296,40.715268
Greece,556,226,40.647482
Norway,574,232,40.418118

In [99]:
python_df.loc[['India','Japan']]

,Number of responded from each country,Number of people knows python,pct_knows_python
India,9061,3105,34.267741
Japan,391,182,46.547315

In [100]:
country_grp['LanguageWorkedWith'].apply( lambda x: x.str.contains('Python').sum() / len(x) * 100 )

Country
Afghanistan                             18.181818
Albania                                 26.744186
Algeria                                 29.850746
Andorra                                  0.000000
Angola                                  40.000000
                                          ...
Venezuela, Bolivarian Republic of...    31.818182
Viet Nam                                33.766234
Yemen                                   15.789474
Zambia                                  33.333333
Zimbabwe                                35.897436
Name: LanguageWorkedWith, Length: 179, dtype: float64

In [102]:
ss = country_grp['LanguageWorkedWith'].apply( lambda x: x.str.contains('Python').sum() / len(x) * 100 ).loc['India']

In [104]:
ss

34.267740867453924